<?php
    if($SessionKategoriAkses=="Anggota"){
        $SessionGambar=GetDetailData($Conn,'anggota','id_anggota',$SessionIdAkses,'foto');
        $SessionNama=GetDetailData($Conn,'anggota','id_anggota',$SessionIdAkses,'nama');
        $SessionKontakAkses=GetDetailData($Conn,'anggota','id_anggota',$SessionIdAkses,'kontak');
        $SessionEmailAkses=GetDetailData($Conn,'anggota','id_anggota',$SessionIdAkses,'email');
        $SessionAkses=$SessionKategoriAkses;
    }else{
        if($SessionKategoriAkses=="Supervisi"){
            $SessionGambar=GetDetailData($Conn,'supervisi','id_supervisi',$SessionIdAkses,'foto');
            $SessionNama=GetDetailData($Conn,'supervisi','id_supervisi',$SessionIdAkses,'nama');
            $SessionKontakAkses=GetDetailData($Conn,'supervisi','id_supervisi',$SessionIdAkses,'kontak');
            $SessionEmailAkses=GetDetailData($Conn,'supervisi','id_supervisi',$SessionIdAkses,'email');
            $SessionAkses=$SessionKategoriAkses;
        }else{
            //Admin
            $SessionNama=GetDetailData($Conn,'akses','id_akses',$SessionIdAkses,'nama_akses');
            $SessionKontakAkses=GetDetailData($Conn,'akses','id_akses',$SessionIdAkses,'kontak_akses');
            $SessionEmailAkses=GetDetailData($Conn,'akses','id_akses',$SessionIdAkses,'email_akses');
            $SessionGambar=GetDetailData($Conn,'akses','id_akses',$SessionIdAkses,'image_akses');
            $SessionLevelAkses=GetDetailData($Conn,'akses','id_akses',$SessionIdAkses,'akses');
            $SessionDatetimeDaftar=GetDetailData($Conn,'akses','id_akses',$SessionIdAkses,'datetime_daftar');
            $SessionDatetimeUpdate=GetDetailData($Conn,'akses','id_akses',$SessionIdAkses,'datetime_update');
            $SessionAkses=$SessionKategoriAkses;
        }
    }
?>